### ISSUE TITLE
`vim.fn.system()` not working as expected.

### ISSUE THREAD

**Issue by theherk** [tadmccorkle/markdown.nvim#8]
[Here in `try_open`](https://github.com/tadmccorkle/markdown.nvim/blob/master/lua/markdown/link.lua#L200), `vim.fn.system` is used to open links in the default browser. But I find it doesn't work correctly for me as it is currently, on either of my machines with 0.9 or 0.10. However, `vim.fn.system("open " .. url)` works. In this case, rather than two arguments, there is one string argument. It could also be a table.

I'm happy to submit this change, if there isn't another reason why this is the way it is. I think it should either be:

```lua
vim.fn.system("open " .. dest)
```

or

```lua
vim.fn.system({"open", dest})
```

**Comment by tadmccorkle** [comment]
Change is welcome. No good reason for current implementation - I didn't have a Mac when I wrote it and couldn't test it. Since the `open` cmd on macOS doesn't, as far as I can tell, support arguments being passed to it from stdin, I wonder if the `xdg-open` branch fails too. If you do submit a change, can you update that branch as well?
